color0 #151216
color1 #ffb4ab
color2 #e8b3ff
color3 #d3c0d8
color4 #f5b7b6
color5 #e8b3ff
color6 #d3c0d8
color7 #e8e0e5
color8 #978e98
color9 #ffb4ab
color10 #e8b3ff
color11 #d3c0d8
color12 #f5b7b6
color13 #e8b3ff
color14 #d3c0d8
color15 #e8e0e5

cursor                #e8e0e5
cursor_text_color     #151216
background            #151216
foreground            #e8e0e5
selection_foreground  #cec3ce
selection_background  #4c444d
active_border_color   #e8b3ff
inactive_border_color #4c444d
url_color             #e8b3ff

active_tab_foreground   #4a1764
active_tab_background   #e8b3ff
inactive_tab_foreground #cec3ce
inactive_tab_background #4c444d
cursor_trail_color      #cec3ce
