-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Max allowed gamma (optional)

-- TODO: manual review: max-gamma = 150

-- Daytime profile (normal colors)

hl.config({
    profile = {
        time = "07:30",
        -- Time time at which the profile should activate
        identity = true,
        -- Ignore temperature value
        gamma = 1.0,
        -- Brightness
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output

-- Evening profile

hl.config({
    profile = {
        time = "21:00",
        temperature = 5500,
        -- Screeen mask, lower means warmer (default = 6000)
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output

-- Night-time profile

hl.config({
    profile = {
        time = "22:30",
        temperature = 5000,
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output
