-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: background = "rgba(151216ff)"

-- TODO: manual review: base = "rgba(151216ff)"

-- TODO: manual review: text = "rgba(e8e0e5ff)"

-- TODO: manual review: alternate_base = "rgba(4c444dff)"

-- TODO: manual review: bright_text = "rgba(392c3eff)"

-- TODO: manual review: accent = "rgba(e8b3ffff)"

-- TODO: manual review: accent_secondary = "rgba(d3c0d8ff)"
